# Generated by Django 2.2.16 on 2022-09-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220928_2017'),
        ('reviews', '0004_auto_20220929_1231'),
    ]

    operations = [
    ]
